Codigo/routes/web.php
<?php

use App\Http\Controllers\ContractorController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function ()
{
    return view('welcome');
});

//rutas para contratistas
Route::resource('contractors', ContractorController::class);

Route::get('/profile', function ()
{
    return view('profile');
});
Route::get('/ver/{id}/{email}', function ($id, $email)
{
    return "Estas viendo el perfil numero " . $id . " con el correo= " . $email;
});

Route::group(['prefix' => 'admin', 'as' => 'admin'], function ()
{
    Route::get('/', function ()
    {
        return view('layouts.main');
    });
    Route::get('/usuarios', function ()
    {
        return "Estas en USUARIOS";
    });
});

Route::get('main2', function ()
{
    return view('layouts.main2');
});

Codigo/app/Models/Contractor.php
<?php

namespace App\Models;

use App\Models\Obra;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Contractor extends Model
{
    use HasFactory;
    protected $fillable = [

        'name',
        'lastname',
        'type',
        'rfc',
        'email',
        'street',
        'house_number',
        'residential',
        'postal_code',
        'city',
        'state',

    ];

    public function obras()
    {
        $this->hasMany(Obra::class);
    }
}

Codigo/app/Http/Controllers/ContractorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contractor;
use Illuminate\Http\Request;

class ContractorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //consultamos TODOS los contractors registrados
        $contractors = Contractor::all();
        return view('contractors.index', compact('contractors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //la accion que devuelve la VISTA pàra crear un nuevo contratista
        return view('contractors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //recibe los datos del  form de NUEVO contractor
        //validar--
        //crear el contractor
        $contractor = Contractor::create($request->all());
        return redirect()->route('contractor.index')->with('success', 'Contratista creado con éxito');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Contractor  $contractor
     * @return \Illuminate\Http\Response
     */
    public function show(Contractor $contractor)
    {
        //muestra los detalle de un CONTRATISTA en particular
        $contractor = Contractor::findOrFail($contractor);
        return view('contractors.show', compact('contractor'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Contractor  $contractor
     * @return \Illuminate\Http\Response
     */
    public function edit(Contractor $contractor)
    {
        //constulrams contratis
        //muestra los detalle de un CONTRATISTA en particular
        $contractor = Contractor::findOrFail($contractor);
        //la accion que devuelve la VISTA pàra crear un nuevo contratista
        return view('contractors.edit', compact('contractor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Contractor  $contractor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contractor $contractor)
    {
        //validar--
        //crear el contractor
        $contractor = Contractor::find($contractor);
        $contractor->name     = $request->name;
        $contractor->lastname = $request->lastname;
        $contractor->email    = $request->email;
        //..
        $contractor->save();
        return redirect()->route('contractor.index')->with('success', 'Contratista modificado con éxito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Contractor  $contractor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contractor $contractor)
    {
        $contractor = Contractor::findOrFail($contractor);

        //si llega todo el BJETO.. sacr el ->id
        $contractor = Contractor::findOrFail($contractor->id);

        $contractor->delete();
        return redirect()->route('constractors.index')->with('success', 'Contratisa eliminado correctamente');
    }
}

Codigo/resources/views/contractors/create.blade.php
Form para crear un nuevo contratista

Codigo/resources/views/contractors/index.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>


<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <table>
            <thead>
                <tr>
                    <td>name</td>
                    <td>lastname</td>
                    <td>email</td>
                    <td>cel</td>
                    <td>...</td>
                    <td colspan="3">acciones</td>
                </tr>
            </thead>
            <tbody>
                @foreach ($contractors as $contractor)
                    <tr>
                        <td>{{$contractor->name}}</td>
                        <td>{{$contractor->lastname}}</td>
                        <td>{{$contractor->email}}</td>
                        <td>{{$contractor->cel}}</td>
                        <td>...</td>
                        <td>
                            <a class="btn btn-success" href="{{ route('contractors.show',$contractor->id)}}">Mostrar</a>
                        </td>
                        <td>
                            <a class="btn btn-primary" href="{{ route('contractors.edit',$contractor->id)}}">Editar</a>
                        </td>
                        <td>
                            <form onsubmit="confirm('¿realmente quieres elmininar?') " action="{{ route('contractors.destroy',$contractor->id)}}" method="POST">
                                <button class="btn btn-danger">BORRAR</button>
                            </form>
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>

    </div>
  <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>